#pragma once

enum REWARD_TYPE {
	REWARD_TYPE_GOLD,
	REWARD_TYPE_PRIZE,
	REWARD_TYPE_TAX,
	REWARD_TYPE_CIVIL,
	REWARD_TYPE_SKILL,
	REWARD_TYPE_CARD,
	REWARD_TYPE_DRAW,
	REWARD_TYPE_UPGRADE,
	END_REWARD_TYPE
};